### PR TITLE
React & Redux group project Space Traveller's Hub

### PR DESCRIPTION
**Pull request by mwafrika**
## Description

In this project, we worked on the real live data from the SpaceX API. we build a web application for a company that provides commercial and scientific space travel services. The application will allow users to book rockets and join selected space missions.

### General requirements

- [x] Followed the **Github flow**.
- [x] There are no linter errors.
- [x] The documentation is professional.

### JavaScript requirements

- [x] Followed list of [best practices for JavaScript](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/javascript_best_practices.md).

### Project requirements

- [x] Used React documentation.  
- [x] Used React components.  
- [x] Used React props.  
- [x] Used React Router.  
- [x] Connected React and Redux. 
- [x] Handled events in a React app. 
- [x] Used styles in a React app. 
- [x] Used React life cycle methods. 
- [x] Applied React best practices and language style guides in code. 
- [x] Used store, actions, and reducers in React. 
- [x] Performed a code review for a team member. 

# [LIVE DEMO](https://space-traveller.netlify.app)

Thank you for taking the time to review this pull request.

### CODE REVIEW

**Comment by omar-labana** [comment]
Hi team, 

Excellent work so far! 👌
You have implemented almost all the required features correctly and without any errors or bugs. ✔️ 
There are some cases that you need to adjust but you are almost done! 😀

## Required Changes ♻️
- [x] I can't seem to find any tests implemented for the project, kindly take another look at the testing requirements for this project.
- [x] Please fic the live version links, it redirects to /dragons

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
_N/A_

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by mwafrika** [comment]
Alright, Thank you for the review @omar-labana  we will work on it

**Review by elisha2kyakpo1 — APPROVED** [review]
Hi 👋 team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by mwafrika** [comment]
It was not easy but we made it.
Thank you @elisha2kyakpo1  for the review
Thank you @mnekx, @zmekonnen251  for being committed and consistent with this project 
We are finally done.
See you next week

**Pull request merged**
